# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - Developerone
  categories:
    - tilte: Breaking Changes
      labels:
        - semver-major
        - breaking-changes
    - title: Exciting New Features
      labels:
        - semver-minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
